[package]
name = "svm-codec"
version = "0.0.0"
authors = ["Yaron Wittenstein <yaron.wittenstein@gmail.com>"]
license = "MIT"
edition = "2018"
readme = "README.md"
repository = "https://github.com/spacemeshos/svm"
homepage = "https://github.com/spacemeshos/svm"
description = "Spacemesh Virtual Machine"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
svm-common = { path = "../svm-common" }
svm-types = { path = "../svm-types" }
svm-layout = { path = "../svm-layout" }
svm-abi-encoder = { path = "../svm-abi/encoder" }
svm-abi-decoder = { path = "../svm-abi/decoder" }
svm-sdk = { path = "../svm-sdk" }
svm-nibble = { path = "../svm-nibble" }
byteorder = "1.3.2"
bit-vec = "0.6.1"
serde_json = "1.0"

[dev-dependencies]
maplit = "1.0.2"