[package]
name = "svm-abi-decoder"
version = "0.0.0"
authors = ["Yaron Wittenstein <yaron.wittenstein@gmail.com>"]
license = "MIT"
edition = "2018"
readme = "README.md"
repository = "https://github.com/spacemeshos/svm"
homepage = "https://github.com/spacemeshos/svm"
description = "Spacemesh Virtual Machine"
publish = false

[dependencies]
svm-sdk-types = { path = "../../sdk/types" }
svm-abi-layout = { path = "./../layout" }
svm-sdk-std = { path = "../../sdk/std", default-features = false }

[features]
default = ["static-alloc"]
debug = ["svm-sdk-types/debug"]
static-alloc = ["svm-sdk-std/static-alloc"]
