[package]
name = "svm-sdk-tests"
version = "0.0.0"
authors = ["Yaron Wittenstein <yaron.wittenstein@gmail.com>"]
license = "MIT"
edition = "2018"
readme = "README.md"
repository = "https://github.com/spacemeshos/svm"
homepage = "https://github.com/spacemeshos/svm"
description = "Spacemesh Virtual Machine"
publish = false

[dependencies]
svm-sdk = { path = "../svm-sdk", default-features = false }
svm-sdk-types = { path = "../svm-sdk/types" }

[dev-dependencies]
trybuild = { version = "1.0", features = ["diff"] }

[features]
default = ["mock"]
mock = ["svm-sdk/mock"]