[package]
name = "svm-sdk-tests"
version = "0.0.0"
authors = ["Yaron Wittenstein <yaron.wittenstein@gmail.com>"]
license = "MIT"
edition = "2018"
readme = "README.md"
repository = "https://github.com/spacemeshos/svm"
homepage = "https://github.com/spacemeshos/svm"
description = "Spacemesh Virtual Machine"
publish = false

[[test]]
name = "tests"
path = "tests/storage.rs"

[dev-dependencies]
cfg-if = "1.0"
trybuild = { version = "1.0", features = ["diff"] }
svm-sdk = { path = "../svm-sdk", features = ["mock"] }
