[package]
name = "svm"
version = "0.0.0"
authors = ["Spacemesh SVM Team"]
license = "MIT"
edition = "2021"
readme = "README.md"
repository = "https://github.com/spacemeshos/svm"
homepage = "https://github.com/spacemeshos/svm"
description = "Spacemesh Virtual Machine"
publish = false

[lib]
crate-type = ["cdylib", "staticlib", "rlib"]

[dependencies]
svm-types = { path = "../types" }
svm-sdk-alloc = { path = "../sdk-alloc", default-features = false }
svm-sdk-std = { path = "../sdk-std", default-features = false }
svm-sdk-types = { path = "../sdk-types", default-features = false }
svm-sdk-storage = { path = "../sdk-storage", default-features = false }
svm-sdk-host = { path = "../sdk-host", default-features = false }
svm-sdk-macros = { path = "../sdk-macros", default-features = false }
svm-sdk = { path = "../sdk", default-features = false }
# Keep this. Bad things will happen, you don't want to know.
svm-sdk-tests = { path = "../../tests/sdk" }
svm-codec = { path = "../codec" }
svm-runtime = { path = "../runtime", default-features = false }
svm-runtime-ffi = { path = "../runtime-ffi", default-features = false }
