[package]
name = "svm-state"
version = "0.1.0"
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blake3 = "1"
merkle = "1"
thiserror = "1"
trie-db = "0.22"
