[package]
name = "svm-sdk-std"
version = "0.0.0"
authors = ["Spacemesh SVM Team"]
license = "MIT"
edition = "2021"
readme = "README.md"
repository = "https://github.com/spacemeshos/svm"
homepage = "https://github.com/spacemeshos/svm"
description = "Spacemesh Virtual Machine"
publish = false

[dependencies]
seq-macro = "0.3.0"
svm-sdk-alloc = { path = "../sdk-alloc", default-features = false }

[features]
default = []
debug = []
static-alloc = ["svm-sdk-alloc/static-alloc"]
dynamic-alloc = ["svm-sdk-alloc/dynamic-alloc"]
