[package]
name = "svm-runtime"
version = "0.0.0"
authors = ["Spacemesh SVM Team"]
license = "MIT"
edition = "2018"
readme = "README.md"
repository = "https://github.com/spacemeshos/svm"
homepage = "https://github.com/spacemeshos/svm"
description = "Spacemesh Virtual Machine"
publish = false


[dependencies]
byteorder = "1.3"
log = "0.4"
lazy_static = "1.4"
prometheus = "0.12"
thiserror = "1"
svm-hash = { path = "../hash" }
svm-types = { path = "../types" }
svm-layout = { path = "../layout" }
svm-kv = { path = "../kv", default-features = false }
svm-state = { path = "../state" }
svm-storage = { path = "../storage", default-features = false }
svm-codec = { path = "../codec" }
svm-gas = { path = "../gas" }
svm-program = { path = "../program" }
wasmer = { version = "2", default-features = false }
wat = "1"

[dev-dependencies]
maplit = "1.0.2"
svm-sdk = { path = "../sdk", features = ["mock", "dynamic-alloc"], default-features = false }

[features]
default = []
default-singlepass = [
    "wasmer/default-singlepass", 
    "wasmer/default-universal",
]
default-cranelift = [
    "wasmer/default-cranelift",
    "wasmer/default-universal"
]
default-memory = ["svm-kv/default-memory", "svm-storage/default-memory"]
default-rocksdb = ["svm-kv/default-rocksdb", "svm-storage/default-rocksdb"]
