[package]
name = "svm-sdk-macros"
version = "0.1.0"
authors = ["Yaron Wittenstein <yaron.wittenstein@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.24"
quote = "1.0.7"
syn = { version = "1.0.42", features = ["full"] }
serde_json = { version = "1.0" }
svm-sdk-types = { path = "../types", default-features = false }
svm-abi-encoder = { path = "../../abi/encoder", default-features = false }
svm-abi-decoder = { path = "../../abi/decoder", default-features = false }
svm-sdk-host = { path = "../host", default-features = false }
svm-sdk-storage = { path = "../storage", default-features = false }
svm-sdk-std = { path = "../std", default-features = false }

[dev-dependencies]
lazy_static = "1.4.0"
trybuild = { version = "1.0", features = ["diff"] }

[features]
default = ["static-alloc"]
ffi = ["svm-sdk-host/ffi", "svm-sdk-storage/ffi"]
mock = ["svm-sdk-host/mock", "svm-sdk-storage/mock"]
static-alloc = [
    "svm-sdk-types/static-alloc",
    "svm-abi-encoder/static-alloc",
    "svm-abi-decoder/static-alloc",
    "svm-sdk-std/static-alloc",
    "svm-sdk-host/static-alloc",
    "svm-sdk-storage/static-alloc",
]
api = []
layout = []
