[package]
name = "svm-sdk-macros"
version = "0.1.0"
authors = ["Yaron Wittenstein <yaron.wittenstein@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.24"
quote = "1.0.7"
syn = { version = "1.0.42", features = ["full"] }
serde_json = { version = "1.0" }
svm-abi-encoder = { path = "../../abi/encoder" }
svm-abi-decoder = { path = "../../abi/decoder" }
svm-sdk-host = { path = "../host", default-features = false }
svm-sdk-storage = { path = "../storage", default-features = false }
svm-sdk-types = { path = "../types" }
svm-sdk-std = { path = "../std" }

[dev-dependencies]
lazy_static = "1.4.0"
trybuild = { version = "1.0", features = ["diff"] }

[features]
default = []
ffi = ["svm-sdk-host/ffi", "svm-sdk-storage/ffi"]
mock = ["svm-sdk-host/mock", "svm-sdk-storage/mock"]
api = []
layout = []
