[package]
name = "svm-cli"
version = "0.1.0"
authors = ["Miguel Angel G. <miguel@gordian.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wabt = "0.7.4"

