[package]
name = "svm-sdk"
version = "0.0.0"
authors = ["Yaron Wittenstein <yaron.wittenstein@gmail.com>"]
license = "MIT"
edition = "2018"
readme = "README.md"
repository = "https://github.com/spacemeshos/svm"
homepage = "https://github.com/spacemeshos/svm"
description = "Spacemesh Virtual Machine"
publish = false

[dependencies]
lazy_static = "1.4.0"
svm-sdk-host = { path = "host", default-features = false }
svm-sdk-storage = { path = "storage", default-features = false }
svm-sdk-std = { path = "std" }
svm-sdk-alloc = { path = "alloc" }
svm-sdk-types = { path = "types" }
svm-sdk-macros = { path = "macros", default-features = false }
svm-abi-encoder = { path = "../abi/encoder" }
svm-abi-decoder = { path = "../abi/decoder" }

[features]
default = []
ffi = ["svm-sdk-host/ffi", "svm-sdk-storage/ffi"]
mock = ["svm-sdk-host/mock", "svm-sdk-storage/mock"]
api = ["svm-sdk-macros/api"]