[package]
name = "svm-codec"
version = "0.0.0"
authors = ["Spacemesh SVM Team"]
license = "MIT"
edition = "2021"
readme = "README.md"
repository = "https://github.com/spacemeshos/svm"
homepage = "https://github.com/spacemeshos/svm"
description = "Spacemesh Virtual Machine"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
derive_more = "0.99.17"
hex = "0.4.3"
indexmap = "1.7.0"
serde = { version = "1.0.133", features = ["derive"] }
serde_json = "1.0.74"
serde_path_to_error = "0.1.5"
svm-types = { path = "../types" }
svm-layout = { path = "../layout" }
svm-abi-encoder = { path = "../../wasm/abi-encoder", features = ["dynamic-alloc"], default-features = false }
svm-abi-decoder = { path = "../../wasm/abi-decoder", features = ["dynamic-alloc"], default-features = false }
svm-sdk-std = { path = "../../wasm/sdk-std", features = ["debug", "dynamic-alloc"], default-features = false }
svm-sdk-types = { path = "../../wasm/sdk-types", features = ["debug", "dynamic-alloc"], default-features = false }
thiserror = "1.0.30"

[dev-dependencies]
maplit = "1.0.2"
quickcheck = "1.0.3"
quickcheck_macros = "1.0.0"
