[package]
name = "svm-cli-craft-deploy-example"
version = "0.1.0"
edition = "2018"
publish = false

[lib]
crate-type = ['cdylib']

[profile.release]
opt-level = "z"
panic = "abort"
lto = true
debug = false
overflow-checks = false
debug-assertions = false
incremental = false
rpath = false

[dependencies]
svm-sdk = { path = "../../../sdk", default-features = false }

[features]
default = ["static-alloc", "ffi", "meta"]
ffi = ["svm-sdk/ffi"]
meta = ["svm-sdk/meta"]
static-alloc = ["svm-sdk/static-alloc"]

[workspace]
