# This file contains settings for `cargo hakari`.
# See https://docs.rs/cargo-hakari/*/cargo_hakari/config for a full list of options.

hakari-package = "svm-workspace-hack"
resolver = "2"
platforms = [
    # "x86_64-unknown-linux-gnu",
    # "x86_64-apple-darwin",
    # "x86_64-pc-windows-msvc",
]

[final-excludes]
third-party = [
    { name = "wasmer" },
]
