[package]
name = "svm-types"
version = "0.0.0"
authors = ["Spacemesh SVM Team"]
license = "MIT"
edition = "2021"
readme = "README.md"
repository = "https://github.com/spacemeshos/svm"
homepage = "https://github.com/spacemeshos/svm"
description = "Spacemesh Virtual Machine"
publish = false

[dependencies]
derive_more = "0.99.17"
hex = "0.4.3"
indexmap = "1.7.0"
svm-hash = { path = "../hash" }
svm-layout = { path = "../layout" }
thiserror = "1.0.30"
