name: SVM CI

# On Rust caching
# ---------------
# <https://github.com/Swatinem/rust-cache> is a very attractive alternative to
# rolling your own caching solution, but it's not very effective for Rust
# nightly and it throws away intermediate compilation artifacts, which might
# result in linkage bugs...

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: False
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        profile: [release]
        include:
          - os: ubuntu-latest
            lib_name: libsvm
            static: a
            shared: so
            target: x86_64-unknown-linux-gnu
          - os: macos-latest
            lib_name: libsvm
            static: a
            shared: dylib
            target: x86_64-apple-darwin
          - os: windows-latest
            lib_name: svm
            static: lib
            shared: dll.lib
            target: x86_64-pc-windows-gnu
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: ${{ matrix.target }}
          override: true
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/
            ./target/
          key: cargo-key-${{ runner.os }}-${{ github.job }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            cargo-key-${{ runner.os }}-${{ github.job }}
      - name: Cargo Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --${{ matrix.profile }} --target=${{ matrix.target }} -p svm-runtime-ffi -p svm-cli --features=default-cranelift --no-default-features
          use-cross: true
      - name: Prepare Artifacts
        run: |
          set -e
          mkdir -p bins
          ls target/${{ matrix.profile }}
          echo "lol"
          ls target/${{ matrix.target }}
          cp target/${{ matrix.profile }}/${{ matrix.lib_name }}_runtime_ffi.${{ matrix.shared }} bins/${{ matrix.lib_name }}.${{ matrix.shared }}
          cp target/${{ matrix.profile }}/${{ matrix.lib_name }}_runtime_ffi.${{ matrix.static }} bins/${{ matrix.lib_name }}.${{ matrix.static }}
          cp target/${{ matrix.profile }}/svm-cli bins/svm-cli
          cp target/${{ matrix.profile }}/svm.h bins/svm.h
      - name: Upload Artifacts
        uses: actions/upload-artifact@master
        with:
          name: bins-${{ runner.os }}-${{ matrix.profile }}
          path: bins/
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: False
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Install Rust
        run: |
          rustup update nightly
          rustup default nightly
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/
            ./target/
          key: cargo-key-${{ runner.os }}-${{ github.job }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            cargo-key-${{ runner.os }}-${{ github.job }}
      - name: Cargo Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all --features=default-cranelift --no-default-features -- --nocapture
  wasm_codec:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: False
      matrix:
        profile: [release]
    defaults:
      run:
        shell: bash
    steps:
      - name: Setup node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Install Rust
        run: |
          rustup update nightly
          rustup target add wasm32-unknown-unknown --toolchain nightly
          rustup default nightly
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/
            ./target/
          key: cargo-key-${{ runner.os }}-${{ github.job }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            cargo-key-${{ runner.os }}-${{ github.job }}
      - name: Test svm-codec
        working-directory: crates/codec/examples
        run: |
          set -e
          ./run.sh
      - name: Upload `svm_codec.wasm`
        uses: actions/upload-artifact@master
        with:
          name: svm_codec.wasm
          path: target/wasm32-unknown-unknown/${{ matrix.profile }}/svm_codec.wasm
  cargo-fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Install Rust
        run: |
          rustup update nightly
          rustup default nightly
      - name: Run `cargo fmt`
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
  cargo-doc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Install Rust
        run: |
          rustup update nightly
          rustup default nightly
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/
            ./target/
          key: cargo-key-${{ runner.os }}-${{ github.job }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            cargo-key-${{ runner.os }}-${{ github.job }}
      - name: Run `cargo doc`
        uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --workspace --no-deps
