name: SVM CI

# On Rust caching
# ---------------
# <https://github.com/Swatinem/rust-cache> is a very attractive alternative to
# rolling your own caching solution, but it's not very effective for Rust
# nightly and it throws away intermediate compilation artifacts, which might
# result in linkage bugs...

on:
  push:
    branches:
      - master
    tags:
      - "*"
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: False
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        profile: [release]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: actions-rs/toolchain@v1
        with:
          target: aarch64-apple-darwin
          toolchain: nightly
          override: true
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/
            ./target/
          key: cargo-${{ runner.os }}-${{ github.job }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            cargo-${{ runner.os }}-${{ github.job }}
      - name: Compile some .wasm
        run: |
          cd simple-coin-transfer-template
          ./build.sh
      - name: Cargo Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release -p svm-runtime-ffi -p svm-cli --no-default-features
      - name: Cargo Build (Apple Silicon)
        if: matrix.os == 'macos-latest'
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --target aarch64-apple-darwin --release -p svm-runtime-ffi -p svm-cli --no-default-features
      - name: Prepare Artifacts
        run: |
          ls target
          ls target/release
          ./.github/copy-artifacts.sh
        env:
          OS: ${{ matrix.os }}
      - uses: msys2/setup-msys2@v2
        if: matrix.os == 'windows-latest'
        with:
          msystem: MINGW64
          update: true
          install: git mingw-w64-x86_64-toolchain mingw-w64-x86_64-tools-git
      - if: matrix.os == 'windows-latest'
        shell: msys2 {0}
        run: |
          cd bins
          gendef.exe svm.dll
          dlltool.exe -d svm.def -D svm.dll -l libsvm.a
      - name: Prepare Artifacts
        run: ./.github/copy-artifacts.sh
        env:
          OS: ${{ matrix.os }}
      - name: Upload Artifacts
        uses: actions/upload-artifact@master
        with:
          name: bins-${{ runner.os }}-${{ matrix.profile }}
          path: bins/
  test:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: False
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Install Rust
        run: |
          rustup update nightly
          rustup default nightly
          rustup target add wasm32-unknown-unknown --toolchain nightly
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/
            ./target/
          key: cargo-${{ runner.os }}-${{ github.job }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            cargo-${{ runner.os }}-${{ github.job }}
      - name: Compile some .wasm
        run: |
          cd simple-coin-transfer-template
          ./build.sh
          cd ..
          cd crates/host/runtime/tests/wasm/calldata
          ./build.sh
          cd ../../../../../..
          cd crates/host/runtime-ffi/tests/wasm/counter
          ./build.sh
          cd ../../../../../..
          cd crates/host/runtime-ffi/tests/wasm/failure
          ./build.sh
      - name: Cargo Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all --no-default-features -- --nocapture
  wasm_codec:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: False
      matrix:
        profile: [release]
    defaults:
      run:
        shell: bash
    steps:
      - name: Setup node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Install Rust
        run: |
          rustup update nightly
          rustup target add wasm32-unknown-unknown --toolchain nightly
          rustup default nightly
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/
            ./target/
          key: cargo-${{ runner.os }}-${{ github.job }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            cargo-${{ runner.os }}-${{ github.job }}
      - name: Test svm-codec
        working-directory: crates/host/codec/examples
        run: |
          set -e
          ./run.sh
      - name: Upload `svm_codec.wasm`
        uses: actions/upload-artifact@master
        with:
          name: svm_codec.wasm
          path: target/wasm32-unknown-unknown/${{ matrix.profile }}/svm_codec.wasm
  cargo-fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Install Rust
        run: |
          rustup update nightly
          rustup default nightly
      - name: Run `cargo fmt`
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
  cargo-doc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Install Rust
        run: |
          rustup update nightly
          rustup target add wasm32-unknown-unknown --toolchain nightly
          rustup default nightly
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/
            ./target/
          key: cargo-${{ runner.os }}-${{ github.job }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            cargo-${{ runner.os }}-${{ github.job }}
      - name: Compile some .wasm
        run: |
          cd simple-coin-transfer-template
          ./build.sh
      - name: Run `cargo doc`
        uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --workspace --no-deps
  release:
    runs-on: ubuntu-latest
    needs: [build, test, wasm_codec]
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/download-artifact@v2
      - run: |
          VER="${{ github.ref }}"
          echo "VERSION=${VER#refs/tags/v}" >> $GITHUB_ENV
      - name: Zip artifact files
        run: |
          set -e
          cd bins-Linux-release
          zip -r ../svm-linux-v${{ env.VERSION }}.zip *
          cd ../bins-Windows-release
          zip -r ../svm-windows-v${{ env.VERSION }}.zip *
          cd ../bins-macOS-release/x86_64
          zip -r ../../svm-macos-v${{ env.VERSION }}.zip *
          cd ../aarch64
          zip -r ../../svm-macos-m1-v${{ env.VERSION }}.zip *
          cd ../..
          cp svm_codec.wasm/svm_codec.wasm svm_codec_v${{ env.VERSION }}.wasm
      - uses: softprops/action-gh-release@v1
        with:
          name: v${{ env.VERSION }}
          files: |
            svm-linux-v${{ env.VERSION }}.zip
            svm-windows-v${{ env.VERSION }}.zip
            svm-macos-v${{ env.VERSION }}.zip
            svm-macos-m1-v${{ env.VERSION }}.zip
            svm_codec_v${{ env.VERSION }}.wasm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
