name: SVM CI

# On Rust caching
# ---------------
#
# We currently use <https://github.com/Swatinem/rust-cache> for caching Rust
# builds. It's easy and very effective.

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: False
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        profile: ["release"]
        include:
          - os: ubuntu-latest
            lib_name: libsvm
            static: a
            shared: so
          - os: macos-latest
            lib_name: libsvm
            static: a
            shared: dylib
          - os: windows-latest
            lib_name: svm
            static: lib
            shared: dll
    steps:
      - name: Cache LLVM (Windows)
        if: matrix.os == 'windows-latest'
        id: cache-llvm-windows
        uses: actions/cache@v2
        with:
          path: |
            C:\\Temp\\chocolatey\llvm
            C:\\Program Files\\LLVM\bin
          key: llvm-windows
      - name: Install LLVM (Windows)
        if: matrix.os == 'windows-latest' && steps.cache-llvm-windows.outputs.cache-hit != 'true'
        run: |
          choco config set cacheLocation C:\\Temp\\chocolatey
          choco install llvm -y
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Install Rust
        run: rustup update nightly
      - uses: Swatinem/rust-cache@v1
        with:
          cache-on-failure: True
      - name: Cargo Build
        uses: actions-rs/cargo@v1
        with:
          toolchain: nightly
          command: build
          args: --${{ matrix.profile }} --package svm-runtime-ffi --features=default-cranelift --no-default-features
      - name: Cargo Build CLI
        uses: actions-rs/cargo@v1
        with:
          toolchain: nightly
          command: build
          args: --${{ matrix.profile }} --package svm-cli
      - name: Prepare Artifacts
        run: |
          set -e
          mkdir -p bins
          cp target/${{ matrix.profile }}/${{ matrix.lib_name }}_runtime_ffi.${{ matrix.shared }} bins/${{ matrix.lib_name }}.${{ matrix.shared }}
          cp target/${{ matrix.profile }}/${{ matrix.lib_name }}_runtime_ffi.${{ matrix.static }} bins/${{ matrix.lib_name }}.${{ matrix.static }}
          cp target/${{ matrix.profile }}/svm-cli bins/svm-cli
          cp target/${{ matrix.profile }}/svm.h bins/svm.h
      - name: Upload Artifacts
        uses: actions/upload-artifact@master
        with:
          name: bins-${{ runner.os }}-${{ matrix.profile }}
          path: bins/
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: False
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Install Rust
        run: rustup update nightly
      - uses: Swatinem/rust-cache@v1
        with:
          cache-on-failure: True
          key: ${{ matrix.os }}-foobar
      - name: Cargo Test
        uses: actions-rs/cargo@v1
        with:
          toolchain: nightly
          command: test
          #args: --all --features=default-cranelift --no-default-features -- --nocapture
          args: --lib svm-sdk-tests
  wasm_codec:
    runs-on: macos-latest
    strategy:
      fail-fast: False
      matrix:
        profile: ["release"]
    defaults:
      run:
        shell: bash
    steps:
      - name: Setup node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Install Rust
        run: |
          rustup update nightly
          rustup target add wasm32-unknown-unknown --toolchain nightly
      - uses: Swatinem/rust-cache@v1
        with:
          cache-on-failure: True
      - name: Test svm-codec
        working-directory: crates/codec/examples
        run: |
          set -e
          ./run.sh
      - name: Upload `svm_codec.wasm`
        uses: actions/upload-artifact@master
        with:
          name: svm_codec.wasm
          path: target/wasm32-unknown-unknown/${{ matrix.profile }}/svm_codec.wasm
  lints:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: False
      matrix:
        profile: [release]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          components: rustfmt
      - name: Run `cargo fmt`
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      - uses: Swatinem/rust-cache@v1
      - name: Run `cargo doc`
        uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --workspace --no-deps
